config/routes.rb
Rails.application.routes.draw do
  

  resources :users
  resources :notes
  resources :books

  resources :users do
    resources :books
  end

  resources :books do
    resources :notes
  end

root 'users#home'
get '/signup', to: 'users#new'
post '/signup', to: 'users#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy' 
delete '/logout', to: 'sessions#destroy'
get '/auth/facebook/callback', to: "sessions#fb_create"
post '/books/new' => "books#create"
  

end

# rails routes can also be navigated through
# http://localhost:3000/rails/info/routes

app/models/user.rb
class User < ApplicationRecord
    has_many :notes
    has_many :books, through: :notes
    has_secure_password

    validates :first_name, presence: { message: "can't be empty" }
    validates :last_name, presence: { message: "can't be empty" }
    validates :email, presence: {  :message => "can't be empty" }, uniqueness: true 
    validates :username, presence: {  :message => "can't be empty" }, uniqueness: true 




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_to_login, only: [:new, :home]

    def index
        redirect_to '/signup'
    end

    def home
        
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_books_path(@user)
        else
            render :new
        end
    end

    private

    def user_params
    
        params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
    end
    

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
    <p>We may have some issues:</p>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li> - <%= message %></li>
    <%end%>
  </ul>
  <br>
  <br>
<%end%>

app/views/users/home.html.erb
<br>
<br>
<br>
<center><h1>Welcome to BookMark!</h1></center>

<br>
<br>
<br>
<br>


<center><p><%= link_to "Sign Up", signup_path%> OR      
<!-- <%= link_to('Log in with Facebook!', '/auth/facebook') %> OR     -->
<%= link_to "Log In", login_path%><br></p></center>

<br>
<br>

<center><h3>You can also sign up with Facebook</h3></center>
<br>
<br>
<center><%= link_to image_tag('https://i.stack.imgur.com/oL5c2.png', width: "350", height: "60"), '/auth/facebook' %></center>
<br>
<br>
<br>

app/views/users/new.html.erb
<br>
<br>
<h1>Create a New User</h1>
<br>
<br>

<!-- <% if @user.errors.any? %>
    <p>We may have some issues:</p>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li> - <%= message %></li>
    <%end%>
  </ul>
  <br>
  <br>
<%end%> -->

<%= render partial: "errors", locals: {user: @user} %>

<!-- <% if show_errors(@user) %>
<%= show_errors(@user) %>
<br>
<br>
<br>

<%end%> -->




<%= form_for @user do |f| %>
    <p><%=f.label "First Name:" %></p>
    <%=f.text_field :first_name, :placeholder => "Enter First Name" %><br><br>
    <p><%=f.label "Last Name:" %></p>
    <%=f.text_field :last_name, :placeholder => "Enter Last Name" %><br><br>
    <p><%=f.label "Email:" %></p>
    <%=f.text_field :email, :placeholder => "Enter Email" %><br><br>
    <p><%=f.label "Username:" %></p>
    <%=f.text_field :username, :placeholder => "Enter Username" %><br><br>
    <p><%=f.label "Password:" %></p>
    <%=f.password_field :password, :placeholder => "Enter Password" %><br><br>
    <p><%=f.label "Confirm Password:"%></p>
    <%=f.password_field :password_confirmation, :placeholder => "Confirm Password" %><br><br>
    <%=f.button "Sign Up", :class => 'btn'%>
<%end%>