config/routes.rb
Rails.application.routes.draw do
  

  resources :users
  resources :notes
  resources :books

  resources :users do
    resources :books
  end

  resources :books do
    resources :notes
  end

root 'users#home'
get '/signup', to: 'users#new'
post '/signup', to: 'users#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy' 
delete '/logout', to: 'sessions#destroy'
get '/auth/facebook/callback', to: "sessions#fb_create"
post '/books/new' => "books#create"
  

end

# rails routes can also be navigated through
# http://localhost:3000/rails/info/routes

app/models/book.rb
class Book < ApplicationRecord
    has_many :notes
    has_many :users, through: :notes
    validate :is_title_case
    validate :is_f_name_upcase
    validate :is_l_name_upcase 
    before_validation :make_title_case
    before_validation :make_first_name_case
    before_validation :make_last_name_case
    
    validates :title, presence: { message: "can't be empty" }
    validates :author_first_name, presence: { message: "can't be empty" }
    validates :author_last_name, presence: { message: "can't be empty" }


    accepts_nested_attributes_for :notes
    
    scope :alphabetize, -> {order(title: :asc)}

    def self.search(search)
      where('title LIKE ?', "%#{search}%")
    end


  private

  def is_title_case
    if title.split.any?{|w|w[0].upcase != w[0]}
      errors.add(:title, "Title must be in title case")
    end
  end

  def is_f_name_upcase
    if author_first_name.split.any?{|w|w[0].upcase != w[0]}
    errors.add(:author_first_name, "Author's First Name must be uppercase")
    end
  end

  def is_l_name_upcase
    if author_last_name.split.any?{|w|w[0].upcase != w[0]}
    errors.add(:author_last_name, "Author's Last Name must be uppercase")
    end
  end

  def make_last_name_case
    self.author_last_name = self.author_last_name.titlecase
  end

  def make_first_name_case
    self.author_first_name = self.author_first_name.titlecase
  end



  def make_title_case
    self.title = self.title.titlecase
  end
    
end





# class Post < ActiveRecord::Base

#     
#     belongs_to :author
  

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :require_login

    def index
        @user = current_user
        if params[:search]
            @books = all_books.search(params[:search])
        else
            @books = all_books.alphabetize
        end
    end

    def new
        
        @book = Book.new
        @note = Note.new
        @book.notes.build
        # binding.pry
        
    end

    def create
        binding.pry
        @book = Book.new(book_params)
        binding.pry
        current_user.notes << @book.notes[0]
        binding.pry
        if @book.save
            redirect_to book_path(@book)
            flash[:message] = "Successful"
        else
            render :new
        end
    end

    def show
        @book = find_book
    end

    def edit
        @book = find_book
    end

    def update
        @book = find_book
        @book.update(book_params)
        if @book.save
            redirect_to book_path(@book)
        else
            render :edit
        end
    end

    def destroy
       find_book.delete
       redirect_to books_path
       #hidden field for [:user_id]
    end

    private

    def book_params
        params.require(:book).permit(:title, :author_first_name, :author_last_name, notes_attributes: [:page_number, :summary, :id])
    end
end

app/helpers/books_helper.rb
module BooksHelper

    
end

app/views/books/edit.html.erb
<br>
<br>
<h1>Let's edit a book</h1>
<br>
<br>

<%= form_for @book do |f| %>
<%= f.label "Title" %>
<%= f.text_field :title%><br><br>

<%= f.label "Author's First Name" %>
<%= f.text_field :author_first_name %><br><br>

<%= f.label "Author's Last Name" %>
<%= f.text_field :author_last_name %><br><br>

<%= f.submit "Submit Book", :class => 'btn'%>


<% end %>

app/views/books/index.html.erb
<br>
<br>
<h1>Welcome <%=@user.first_name%></h1>
<br>
<br>


<%= form_tag("/books", method: :get) do %>
Search By Title: 
<br>
<br>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag 'Search', :class => "btn"%>
<% end %>






<!-- <p>Show all books with notes underneath here, and make sure you have the logout button within the navbar, also, want to have a button such as to add a book, and to add a note to the book right after the note, also want to make sure to add a error message<p> -->
<br>
<br>

<% @books.each do |book| %>
<br>
<ul>

<h3><%= link_to book.title, book_path(book) %> - <%= book.author_first_name %> <%= book.author_last_name %><br><br></h3>

<% book.notes.each do |note| %>

<ul><p><%= note.summary %></p></ul>

<%end%>
<br>

<!-- display the last note submitted -->

</ul>
<% end %>

<!-- when i add a new book, add flash[:message] Successfully Added -->

app/views/books/new.html.erb
<br>
<br>

<h1>Let's Add A New Book</h1>
<br>


<% if @book.errors.any? %>
    <p>We may have some issues:</p>

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li> - <%= message %></li>
    <%end%>
  </ul>
  <br>
<br>

<%end%>




<%= form_for @book do |f| %>
<%= f.label "Title" %>

<%= f.text_field :title, :placeholder => "Enter Book Title" %><br><br>

<%= f.label "Author's First Name" %>
<%= f.text_field :author_first_name, :placeholder => "Enter Author's First Name"%><br><br>

<%= f.label "Author's Last Name" %>
<%= f.text_field :author_last_name, :placeholder => "Enter Author's Last Name" %><br><br>

<%= f.label "Page Number" %>
<%= f.fields_for :notes do |n| %>
    <%= n.text_field :page_number, :placeholder => "Enter Page Number" %><br><br>
    <%= n.label "Summary" %>
    <%= n.text_area :summary, :placeholder => "Enter Summary..." %><br><br>
    <%end%>

<%= f.submit "Submit Book", :class => 'btn' %>

<!-- fields_for @notes, we want to make sure to add notes on the book -->

<!-- have to add a hidden field relating the book to the user -->

<% end %>

app/views/books/show.html.erb
<br>


<% if flash[:message] %>
<br>
<h4><em><%= flash[:message] %></em></h4>
<br>
<br>
<%end%>

<br>
<h3><%= @book.title %> - <%= @book.author_first_name%> <%=@book.author_last_name%></h3>
<br><br>
<% @book.notes.each do |note| %>
<br>
<p><%= note.summary %></p> <%=link_to "Edit Note", edit_book_note_path(@book, note) %></li>
<br>
<%end%>
<br>
<br>
<br>



<%= link_to "Add Note", new_book_note_path(@book)%>
<%= link_to "Edit Book", edit_book_path(@book) %>
<%= link_to "Delete Book", @book, method: :delete, data: { confirm: "Really?" } %>