config/routes.rb
Rails.application.routes.draw do
  

  resources :users
  resources :notes
  resources :books

  resources :users do
    resources :books
  end

  resources :books do
    resources :notes
  end

root 'users#home'
get '/signup', to: 'users#new'
post '/signup', to: 'users#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy' 
delete '/logout', to: 'sessions#destroy'
get '/auth/facebook/callback', to: "sessions#fb_create"
post '/books/new' => "books#create"
  

end

# rails routes can also be navigated through
# http://localhost:3000/rails/info/routes

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <!-- <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.5.1.slim.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"  %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" %>  -->
    <link rel="stylesheet" href="/stylesheets/main.css" />
   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="wrapper">
<% if !current_user %>
      <h4><span><%=link_to 'Home', root_path%></span></h4>
<% end %>

  <% if current_user %>
    <div>
      <h4><%=link_to 'Home', root_path%></h4>
      <h4><span><%=link_to 'All Books', user_books_path(current_user)%></span></h4>
      <h4><span><%=link_to 'New Book', new_book_path%></span></h4>
      <h4><span><%=link_to "Logout", logout_path, method: :delete, data: {confirm: "Really?" } %></span></h4>
    </div>
    <%end%>

    <%= yield %>
    <footer class="branding">
        <small>&copy; 2020 <strong>BookMark</strong></small>
      </footer>
    </div>
  </body>
</html>